name: Nowy Database

env:
  DOTNET_VERSION: '7.0.103'                 # set this to the .NET Core version to use
  BRANCH: ${{ github.ref_name }}

on:
  push:
    branches: [ "main", "tobias" ]
    paths:
      - 'src/Nowy.Database*/**'
      - 'src/Nowy.Auth*/**'
      - 'nukebuild/**'
      - '.github/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - uses: actions/checkout@v3
        with:
          path: nowy_database

      - name: Cleanup
        run: rm -rf ~/.dotnet/toolResolverCache

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          if_key_exists: ignore

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: global.json
        run: cp nowy_database/global.json .

      - name: Run './build.cmd Deploy'
        run: cd nowy_database; export PATH="$PATH:$HOME/.dotnet/tools"; ./build.cmd Deploy
        env:
          NuGetAzureDevOpsPassword: ${{ secrets.NUGET_AZUREDEVOPS_PASSWORD }}
          NuGetOrgApiKey: ${{ secrets.NUGET_ORG_APIKEY }}

      - name: Publish
        run: rm -rf ./myapp ; dotnet publish -c Release -r linux-x64 -o ./myapp nowy_database/src/Nowy.Database.Web/Nowy.Database.Web.csproj

      - name: List published
        run: find ./myapp

      - name: Branch
        run: echo Branch is ${{ github.ref_name }}

      - name: Upload (host key)
        run: |
          ssh-keyscan -t rsa nowy01.server.nowykom.de >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa nei0.server.schulz.dev >> ~/.ssh/known_hosts

      - name: Upload (transfer files)
        run: |
          rsync -avz --update myapp/ root@nowy01.server.nowykom.de:/srv/nowy_database/${BRANCH}/web/  --no-perms --no-owner --no-group --delete --exclude database --exclude files
          rsync -avz --update myapp/   root@nei0.server.schulz.dev:/srv/nowy_database/${BRANCH}/web/  --no-perms --no-owner --no-group --delete --exclude database --exclude files

      - name: Upload (fix permissions)
        run: |
          ssh root@nowy01.server.nowykom.de 'chown www-data:www-data -R /srv/nowy_database/ ; service nowy_database_'${BRANCH}' restart '
          ssh root@nei0.server.schulz.dev   'chown www-data:www-data -R /srv/nowy_database/ ; service nowy_database_'${BRANCH}' restart '

      - name: Cleanup
        if: always()
        run: rm -rf nowy_database


